"""change hash string size

Revision ID: 1a4fd4121f4a
Revises: d6bd52cb11c0
Create Date: 2025-08-23 21:19:36.125891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a4fd4121f4a'
down_revision: Union[str, Sequence[str], None] = 'd6bd52cb11c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

## Fixed with ChatGTP
def upgrade():
    with op.batch_alter_table('perfums') as batch_op:
        batch_op.alter_column(
            'hash',
            existing_type=sa.String(length=128),
            type_=sa.String(length=32),
            existing_nullable=False
        )

def downgrade():
    with op.batch_alter_table('perfums') as batch_op:
        batch_op.alter_column(
            'hash',
            existing_type=sa.String(length=32),
            type_=sa.String(length=128),
            existing_nullable=False
        )

# Autogeneratecode with alembic revision --autogenerate
#
# def upgrade() -> None:
#     """Upgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.alter_column('perfums', 'hash',
#                existing_type=sa.VARCHAR(length=128),
#                type_=sa.String(length=32),
#                existing_nullable=False)
#     # ### end Alembic commands ###


# def downgrade() -> None:
#     """Downgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.alter_column('perfums', 'hash',
#                existing_type=sa.String(length=32),
#                type_=sa.VARCHAR(length=128),
#                existing_nullable=False)
#     # ### end Alembic commands ###
