"""initial schema

Revision ID: 1c4b6a308c2c
Revises: 
Create Date: 2025-09-02 02:20:15.547502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c4b6a308c2c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('merchant',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('perfum',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('edt', 'edp', 'parfum', 'elixir', 'extract', name='perfumtype'), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('sig', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sig'),
    sa.UniqueConstraint('sig', name='uq_perfum_sig')
    )
    op.create_table('merchant_perfum',
    sa.Column('merchant_id', sa.Integer(), nullable=False),
    sa.Column('perfum_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchant.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['perfum_id'], ['perfum.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('merchant_id', 'perfum_id')
    )
    op.create_table('price',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('perfum_id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['perfum_id'], ['perfum.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('price')
    op.drop_table('merchant_perfum')
    op.drop_table('perfum')
    op.drop_table('merchant')
    op.drop_table('brand')
    # ### end Alembic commands ###
