"""Unicitity constrain in hash column of perfums' table

Revision ID: 3e819074fc90
Revises: 1a4fd4121f4a
Create Date: 2025-08-23 23:07:47.806152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e819074fc90'
down_revision: Union[str, Sequence[str], None] = '1a4fd4121f4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    with op.batch_alter_table('perfums') as batch_op:
        batch_op.create_unique_constraint('uq_perfume_hash', ['hash'])

def downgrade() -> None:
    """Downgrade schema."""
    with op.batch_alter_table('perfums') as batch_op:
        batch_op.drop_constraint('uq_perfume_hash', type_='unique')

# Autogeneratecode with alembic revision --autogenerate
#
# def upgrade() -> None:
#     """Upgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.create_unique_constraint('uq_perfume_hash', 'perfums', ['hash'])
#     # ### end Alembic commands ###


# def downgrade() -> None:
#     """Downgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.drop_constraint('uq_perfume_hash', 'perfums', type_='unique')
#     # ### end Alembic commands ###
